### ISSUE TITLE
Acid cauldron causing ticking entity

### ISSUE THREAD

**Issue by mxnmnm** [MehVahdJukaar/amendments#22]
I am using neruina so it didn't crash, but it probably would otherwise.

This is the server log
https://gist.github.com/mxnmnm/1661d4493735e47cb002dd130c84941f

**Comment by MehVahdJukaar** [comment]
fixed

**Comment by mxnmnm** [comment]
https://gist.github.com/mxnmnm/5ba52a1eb3840f09d157b8abb7b22b84 not fixed :(

**Comment by mxnmnm** [comment]
this seems to only happen when using a dedicated server and not singleplayer

**Comment by mxnmnm** [comment]
https://gist.github.com/mxnmnm/fa8092c9aeacf64b18cb744b7d76ea2d
